# Site settings
title: DiversifyMicrobiology
email: diversifymicrobiology@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   The website for DiversifyMicrobiology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://DiversifyMicrobiology.github.io" # the base hostname & protocol for your site
twitter_username: DiversifyMicro
github_username:  diversifymicrobiology 
array: []

# Build settings
markdown: kramdown

collections:
  instructors:
    output: true
  workshops:
    output: true
  news:
    output: true
